// Generated by wrangler types or manually defined
// This file provides type definitions for Cloudflare Workers environment bindings

/// <reference types="@cloudflare/workers-types" />

interface Env {
	// Durable Object binding for MCP agent
	MCP_OBJECT: DurableObjectNamespace;

	// KV namespace for storing encrypted OAuth tokens
	OAUTH_KV: KVNamespace;

	// Encryption key for AES-GCM (64-char hex string = 256 bits)
	COOKIE_ENCRYPTION_KEY: string;
}
